language: java
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report

# run in travis' container based infrastructure; we don't have sudo there
sudo: false

before_deploy:
  - export Project_CRUD=$(ls target/SimpleCrud.war)

deploy:
  provider: releases
  api_key:${GH_Token}
  file:"${Project_CRUD}"
  skip_cleanup: true
  on:
    repo: clydegold8/Simple-MAVEN-SPRING-OBJECTDB-CRUD
    tags: true
