language: java
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report
before_deploy:
  - export Project_CRUD=$(ls target/SimpleCrud.war)
deploy:
  provider: releases
  api_key:32bb9390426000dfe9fb2e1247bd99f15fe07e47
  file:${Project_CRUD}
  skip_cleanup: true
  on:
    repo: clydegold8/Simple-MAVEN-SPRING-OBJECTDB-CRUD
    tags: true
