language: java
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report
deploy:
  provider: releases
  api_key: ${gitApi}
  file_glob: true
  file: ./target/SimpleCrud.war
  skip_cleanup: true
  on:
    branch: master
